version: '3'

services:
  backend:
    container_name: api
    env_file:
      - ./backend/.env
    build: ./backend
    ports:
      - 3001:3000
    restart:
      on-failure
    depends_on:
      - mongodb
    networks:
      - api-db
      - main

  mongodb:
    container_name: database
    image: mongo:5.0.16-focal
    networks:
      - api-db
    restart: unless-stopped
    volumes:
      - mestodb_data:/data/db:rw

volumes:
  mestodb_data:

networks:
  api-db:
    driver: bridge
    internal: true
  main:
    driver: bridge
